/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "Auth": {
        "region": "ap-south-1",
        "userPoolId": "ap-south-1_6wG9MjgEg",
        "userPoolWebClientId": "6iej1mpkfga9uikepq6fh1n1b0",
        "identityPoolId": "ap-south-1:ed495a11-8f04-4c83-ad21-de42d1b48500"
    }
};


export default awsmobile;
